sample = """##################################################################################################################################################
##################################################################################################################################################
##################################################################################################################################################
###SSSMXMMSMMXXXSMXMASXSAXXMSXSMSXMMSSMMMSMAMXMASASXSXMMSXXXMAXSMSXMAMSAMXMSMAMSAMAMMXSAMXMMSAMMMMSMMMSMMXMMSSMMXSMAMMAAMAMXSSXXXAMXXXSASMSSSSS###
###MAASXMASAMXMXMMMXMMMSSMAXSAMXSAXMASAAAXMAAMMAAASMSAMSMAMSMMMXXXAMMMXMXMXAMAMAXMAXXAMXMAMXMAMAASXMAAAMXAMXAAXSAASASXMSMSXMXMASXSASMMMAMAAAAAA###
###MSMMMMMSMMAAAAAMASAMMAXXXMAMASXMMXSXMMSSSSXMXMMMASAMXMAMAAASXSXMMSXAAAMSMSAXMMMSSMASASMSSSSMSXSASMSSXXASMXSMMMXMXMAAMXMASAMXMAXASXAMAMMMMMMM###
###AAAXAAASXSXSMSASASAXXAMXMSAMXSSMSMMXSXAAAMXMAMASXSAMXSASMSMSAMXMAXSXMAXAAXAMXAMAAXMMMSAAAAXAMASAMXAAASAMMXXAMXAMSXMMMASMMASXMMMAMXXMXSXXXAMX###
###SXSSMSXSAMAMXXXMMSASAMXAXAASAMXSAMXAXAMSMMASASASXMAMASASAMXMXMAMMXAMXSSMXMSASMMSSMXMXXMMMMMAMMMMMMMSMAAXSASAMMSXSAAMSAMASAMAAXMSMSSMSMMMSMMX###
###AAXMAMXMXMAMMSAXAMASMASMSSSMASXAXMXXSXXAASXMASAMMMSMASASMMSSSSXSXSASAMAASAMMSAAAAMAMXXXXMAMXSMXSAMXXXMAXMASMMAXASAMMMXSXMASMMMSAMAAMSAAMASXM###
###MAMSASAMAMXSAMXMXSAMXMAXXMAXXMAXSMXAMMXSXMXMMMMMAMAAMMXMAAAXAMXAASAMXMMMAAMXMMMMSSXSXXSSSXSASXAMAMASAXMSMXMAMAMAMAMXMASASAMXAMXASXXMMSMSASXA###
###AXMMMMAMXAAMASAMXMASXSMSSSMSMSMAAAXXMAAXAMASAAASXMXXMAMSMMSSSMSSXMXMSXMSMSSSXXXAXMXMMXSAAAMAMMMMXMMSMMMAMXSAMSMMMAMAMASXMXASXSMMMAMMXMXMAMMM###
###SXMAMSSMMMXSMMXMAMXMXASAAXAAMAMXAMXMMSXSASAXASMSXMSXMXAAXMAAAMAMXMXAXAXXXXAMAMAMMMMSASMMMXMAMAXSMSASAXMAXXMXSMAMSMSAMXSXMXMMMSMSAMSMAMXSMMXS###
###XASAMAMXXMAMXMSSXSASXMMMMMXMSXMXMMXSAAMSAMMSAAMXAAMAMXSMSSMSMMSSSMASMXMMAMMMXMASAMMMXSAXXXXXXMSAAMASASMSMXXMAXAMAMAMXAMAMXAAAMASMMAXASXXAMAA###
###SXSASMMMSSMMSMMAASAMAXSASAXMXXMAAAAMAMXMXMXAMMSSMMSMMAXMAXXXAAXAAXAXMAMAAXAAASXSXSAMXSXMXSXSMXMMSMXMAMAAXSXSXSXSXSMAMMSASMSMSMAMASXSXSAMMMMS###
###SASXMXAAMAXMAAMMMMXSXMSAMASMAASMMMSSSMXSAMXMSAXXMMAAAXSXSXMXMMMSMMMXSAMSMSSSXSXSASMSMSXMXSAAMSXXAMMMSMMMMXAXAMAMAMXXXMSAXAAAXMASXMXXAXMASAXA###
###MAMXMMMMSAMSSSMMXSAMXXMAMSMMMMXSAAAAAMAMAMXXMMXSASMSMSSMMASXAAAAAAAAXXMAXXXMASXMAMAMAMMMAMSMMSMSMSASAMMAMMMMMMAMAMSSMMMXMSMSMMMSAMXMMMXXSASA###
###MAMAMXMAMAMXAAXMAMASAXMAMXAXSXASMMMMMMASAMXAAXAXMAXAXAMAMAMSSMSSSMSSMMSMXMMMAMXSMMXMAAAXXXAMXXAAASXMAMSASAAAXSXSMSAXAAAMXXMAXXASAMAMSASMMMMM###
###SASAMASASAMMMMMMASXMMSSMXSAMXMMXSAXXXSASASAMXMMSXMMMMMSSMAMAMXAMAMAMXXASAAXMASMSAXXSMSSSMXSMMMSMMMMSSMSASXSSMMASXMMSSMSMSAMMMMMMAMAXAAXXAXAX###
###SXSMSMSXSXMSASXSAXAAAMAAXMSMXASASXSMAMAMAMXMASAAMXASAMAXSAMAMAMSXMASXSASMSXSXMAXMMMAAXAAXAMAMAMMXMXAMXMAMMMMAXAMAAXMAMAASAMAXAAXMMMSMMMSXSXS###
###SXMAAAMAMXXXAXAMASXMXMAMXXAXXSMASAAMXMAMXMMSAMSSXSXXASMMSMSMSSXMMSASXMXMXXAXAMAMSMSASMMMMXMAMXSMAMMMSAMAMXASXMAMAMXXMMSMSMMMSMSAAAAAMXAMAXAM###
###MAMSMSMMSSSMSMAMMMAAAMSXSSMSXXMAMMMXXMASXAAMMMAXMXXSMMXAMXMAMMASAMMSMSASAMMMMMXSAAXMMAAMXSXSSMXMAMMXSXSXXMMAXXSMSMSSMAMAXXAXAAXMSMSMSMMSSMAM###
###MAMXAXXXAAAAAMMMSSMMMMMAMXXSXMMSSXSAMXAMMMMSSSMMMAASASMXSAMAMXAMMMMXAXAMXSXAAMXMMSMMSSMMASXAXXAXMSMAMXMXAXSXSXMAAAAAMAMMMXMSSMMXMAMASAXAXAAA###
###SASMMMSMMSMMMSSXMAXSAAMAMMAMAXXMAXAXMMASMSSXAXXAMAMSAMXAXASMSMMSXAXMSMXMXMMXMXAMXAXXAAXMASMAMSMMSAMASAAXMMSAMASXMMMMMXSXSXMAAXXXMAMXMXMASMXS###
###SXXAXAXAXXASXAAASMMSMSSSMMASXMMSSMSXSAXMASAMXMMMSXXMAMMMXMMAAXAMMXXAXAAMXMASXMASMMMSSSMMASAAAXAXXAMSSMSXXAMAMMMAXXMASMMASAMSSMMMMSSMAXMXSAMX###
###SXSMMXSSMSAMMMSMMAMXMMAMAMASXAMMMAAAXXXXXMXSXMMAXMASAMXAAMMMMMXSASMMMMXSXAMAMSAMASAMXXAMMMXSXSMASXMAXAXMMMXAMAXSMMSASAXASMMAAAAXAAMXMASAMASM###
###XXAAMXMMAMXMAMAASMMSXMXSXMASMSMAMMMSMMMXMMAMMXAMSXASAMMSXSAMXMXMASXSAXSAMXMAXMASAMASXSMMSMMMMAAAAAMMMMAXAMXSSXXMAMMMSXMXSXMSSMMMMMMAMAMAXAMX###
###SMSAMASAMXASASMMMAAMXMAXAMXSXAMASAAXMAAAXMAMXMMSXMXSAMAAASXMAMSMMMXAXMAAMXMXMSAMXSAMXAMAMXAMSAMMMMMXASAMSMAMAMASAMAASAMXSAXAXAAMAASXSSSSMMSX###
###SAMMSAXSAMXSXSXASMMMAMASXMXSXMXAMMSSSSMMSSMMSASMMSMSMMXSAXXXAXAAAXSMXASAMXMMMMXSMSXSSSMSSMMXMXXAAXXSXSMAAMMSASMXASMMMASASMMXSMMSMXSAAXAXMMMX###
###MAMAMASAMXMXAXMASMXXASMAASXSASMMXAAMMMAAXMXAXMAXXMAMXAMXMAMSMSSXMXAXMMXXMAXAMXMMAMAMAAAMMXMAMMMXMXAMXMMSXSMMAMXSXMMMMAMASXMMAMAXAXMMMMAMMAMX###
###SAMAMMSXAAMMXMMMMMMSMSMSXSASAMASMMMSASMSMSMMXSSSSMMMMMXAMXXAXXAASXMXSAMASMSSMSMMSMAMXMASMASXSASAAMSMSXAMXSAMXMXMASASMSMMMAMMMSXSMMMXAAAASASA###
###SXSSSMMMSAMXASXAAAAAASXMASAMAMAMASAMXSAAAAASAMAAAAXMAMMSMMSMXMSMMAXAMASAMMAMXAAXXXXSXSAAXXSAXASMXMAAMMSSMMASMMMSMMAXSAAAXAMSMMAMMAXMAXMXSASM###
###XXAMXAAAAAMSMSSSMSXMXMAMAMASXMXSAMASXMXMSMAMMSMSMMSMXSAXAMXSAMASMXMMSAMMSMAMMMMMMSXMAMSSXXMAMXXMASMSMAXAASAMAAAAXMXMXSSMSMSMAMMMSMSAXXSAMAMX###
###SMSSSSSSMAMAAMAXAMXSAMAMXSXMAMAMMSMMMSAMXXSXXSAMXMAAAMASMMASXSASMAAAMAXSAMMSXMAMAAAMXMMMXAMXMSASAMXXMXSAMMMSSMSSSMAMMMXMAXAMSMSMXMMMASMASXMS###
###XAXAAXMAXAXMMMAMXMASAXXXMXAMXMMSASAAASASAAXXSMMMSSMSMAAMAMASXMXMMXMAMXMMASAAASAMXSSMAMAAAXXAAXAMXSAMXXMASMAAMAAXAXXXASASMXMMMAMAMXMAMASMMMMX###
###MSMMMMSMMMSSSMXSAMXMAAMSSSXSASXMAXSMMXXMASMMXAAAXAXAXMXSXSXMXXXAAXAMSMSMSMMMXSAXAXMAMSMMSMSASMAMAMXSSMMAMXMASMMSSMSMAMMMXXMAMSMSSMSXXMAXAAMX###
###MAMXAAXXMSAAXAXSXSAMXSAAMAAXASMMMMMMXSSXXAAXASMSSMMAXXMMASAXXMMSMMMXAAAXAAXXAXAMSSXSXSAMXAMAXXSMASASASMXSXXXXAXXAAAMXMSMSASXSAAAAAAASXSMXMXM###
###SAMXMMSAMMMXMMMMMSXSAMMXMMMMSMXAMAXSAXMASXSXMMAXXXMSXXASAMAMXXAAAAAMMSMXSXMMMXAMXAXMMSAMMSMAMMXSASMSAMXMAXMMSMMSMSMSAAAAXMASMMSMMMXSAAMASXSM###
###MASXAMMAXXXXAAAMAMAMXMAMXAAXMASMSSXMXSXXMXMAMXXMSXMAASMMXSAXXMSSSMSXXAAAMXMASXSXMMXMAXMMSAMXXXAMXSAMXMMXMASAAAXMAMASXMMXMXMAXXAXXXXXMAMASAAX###
###SAMXMXSMMMXXXMXMASXMSMSMSSSSMXMAAMXSAMXSMXSAMXAMXAMMMMXAXSAMXXMAXAXMMMMMXAMASAXXXXAMMSSMSMSMMSMSAMXMSXMASMMXXSMXAMAMMXSSMAMMSSMSSXMXMMSAMXMM###
###MXSXXAXAAAXMSSXMXSAASAMXAXMXMSMMMSMSAMASXAMASXAXSSMSXMMSMMMMMXMXMXAXXXAMAXMASMMMMSXSXAXASXSAAXMMXSSSMAXAAMASMXMMMSXSXAAXSASXAXMAMMAXXAMAMXSM###
###ASXMMSXSMSASAAASMMMMMAMMSSMAMMXXAAMXMMASMMSAMXMMMAAXMAAXAMASXSAXMMSMMSASMXMAXXAAXMAMMMMMMASMMXSXMAXAASMSSMAXXAMAMXAXMMMXMMSMXSMAXSXSMSSSMASX###
###XMAMXMAXAMMMMSMMAAXAXXMXMMXAMXXMSMSSSMASAMMMMXMASAMMAMMSMSAXSAMXXAAAXAXAXAMXSSSSSXMSMMMXMAMAAASAMXSSMMAXXMASMMMSSMMMXXSMSMXMASMMXMAMAAAAMXMM###
###SSMMAMSMMMAAXMMMMSSMSMSSSSSMSXMAMXAAXMXSMXSSSMMAXAMXXAAMAMXSXMAMMSSSMMMMSMSMAAXXMMMAAASAMXSXMXSAMMXMAMXMXMAXAAAAAAXAXXMXAAXMASAMAMAMAMSMSASX###
###XAMMXMAAASXSSMASAAAXAAXAAMAAMMASXMMSMXMSAXAAAXMSMMMSMSAMXMSAXXSXAAXAAXAXAAAMXMXMMAXSXMMAXXSMSASXMMAXMMMSAMXSMMMSSMMSMASMMMXSMSMMMXAXXXAMXASX###
###SMMASXXXMAAMXXAMMMMMMSMMMMMMMASXSMAAAXAMXMMSMMXAASAMAASXAMSMSMAMMSSSMSSSMXMXMXXMASXMASXSMAXAXXSXSMMMXAXMAMASMAXXMMAMXMSAAAXXAMASXSMSMMMSMMMX###
###XAMASMSMMMXMAMMXSAMSXXAXXXMXMSAMAMMMXAMXXMXAXAMSXMASMMXSMAXXAMMAMAAAAXMXMASMSAXXXXASAMAXMSMSMASAMASMSSMSAMAMXXMAAMASMXSMMMSMAMXMAAAAAXAAAAXM###
###SSMMMAAXMXAMXMXAMAXSASXSSMMAXMASMMMAMSSMXSXSXXAMXSAMXXXAMAMSMSXSMMSMSMSASASAMASMMMMMXMMMXXAMMAMAMAMAAAAXXMMMSMSXMXAMAMMMSAXXXMXMXMSSSMXMXMMX###
###AAAMMSMSSSMSAMMMSAMMAMAXMASXXSMMXASMXAAMASMAMSSXMSAMMSMXAAMAXSAXXAAXXASASAMXMXMXAAXMAMXMMMSMMXSXMASMMMMXSAAASXSMSMMSSXMASAXXMMAAMXMAAAXSSSMS###
###SSMMAXXAXAXSMSMMSXSMAMXMXMMMXAXMSASXMSSMASMAMXMAMSAMMAAASMSMMXXSMXSXMAMMMXMXXXXSXMMSAXAAAXAXMAMAMASXXMXMMAMXXASASXMAXAMASMSAASASMAMSMMMAAAXA###
###MAMMXSMXSMMMXMMAMXSAMSXSXMAAMMSMAXMAXXXMASXMXSAMXSAMSMSMXXAXSSMXMAMXMSAMXMMMMMMSAMXSMSSSSSSSMXMAMMSXMXAXXXMSXAMMMAMASASAMAAMXMAMXAMAASAMSMMM###
###MAMXAAAMSASXAXMMMAMSMMAMAMMSMAAXMAXMMAXMASAMASAMXMAXAAXMXSMSMMAAMASAXXAXXAAAAAASMMXSAAAAAAMAAAXAXXXMMSMXXAAXMMMXSMMMMMMAMAMXXMMMSMSSSMSXXAMX###
###MSMMASXXSAMMMMMMMXSAMXAMAMXAMSSSMSSMSXXMASAMMSAMMXSSSXXMAMXMXASASAMAMMMMSSSSSMMSXMXMAMMMMMMMXMASMMAAXAAASMSMAAAXMASAAXSXMSXXSSSMAXAXMAMXMASA###
###AAAXXMAXMSMAMASAMXAMSSSSXXSXMAAAXAAXSAMMASAMXSXMMSMAMSXMMXAMXXXAMXSAXAAAMXMXAXAXAXAXXMXMAMAXXXAXAMXSSMSMAAAXXXSMMAMXSMMASAMSMAASMMMSMAMAXAMA###
###SSMMMAMXXAXXSASAXMMXAAXMAXMMMMSMMMSXXAMAXSMSAMAXXAMAMXSXSSMSAMMAMASXXXMMSAMMSMSXMMSMMMXSXSXXXMAXASXMXMAXMSMSASAXMASMMASMMSXAMSMMXAXAMMSSMMSS###
###XAXAXSXMSMSXMASMMSXMMSMMMSMAAXAAXXMAMSMXXSMMASAMSXMASMMMAAAXAXSXMXMMMSAAMAMAXMXAAAXAAMASMAXSSMSSMMXMASMSMAXSMMAXSXMAXMMXAMSMXMXXXMSSSXAXAXAX###
###XAMXMXAMXXAAMXMXAAAXMAMAAXXXSSMSXMAMXAAXAMASXMAMAASASAAXMSMMMMMXMAAAAXMXMSMMSASMMMSSMSASMAMXAAAXASMSAMXAXMXMXMAMXMMSMASMSMAMAMSMSMAMMMMSAMXS###
###XSMSSSSMSXSSXSAMMSXMXAMASXXSAMMAASAMMMMAASAMXSXMMXMASXMSXAAASAMAMXMMSSSMAMAMMAMXAXXXAMAXMASMMMMSMMAMASXXMSAMXXXMAMAMMMMAXSMSMSMAAMAMAAXAXMXA###
###AMAMAXMASAAXAMAMXMMMSMXAMAXMASXSMMAXSAMSXMAXXMMMMSMAMASXXMSMSASMXXASAAAMAMAMXMMSSMMSXMMMSMSXMAXXAMXMMSAMXSMSSSSSSSMSAXMSMXXXXMMSMSMSXXMMXMMA###
###MMAMMMXAMMMMXMASMAAMAMMSMMMMAMAMASAMSAAAAMSMSMMSAMMSSMSASXMMSAMAAASMMSMMSMMMXXAXAAASAAXAXXSASMSSXMSMMMAXMXXAAXAAAAASAXMAMMMSSMAMXAAXXSSXMSAS###
###XSXSXMMSXAXXXMAMMSMSMMMAAXSMSMXSAMAXSMMSSMXAAAAMASAAAXMAMMMAMSMMMMXAXMXMXASAMMSSSMMSSMMMXASAMAXXXXAXASMMSMMMSMMMMMMMAXMASAAAXMAMXMSAMXAAAAMM###
###MAMXAXAXSSSSMMAMXMAMMASMSMAAAXXMMMXMXSAMAAMAMMMSMMMXXAMXMAMASXXXXXMSMXMMXAMASAAAXXMXMMASAXMAMXMMSSMSXMMAAAMAAAAXASAMXASASMSSSMASAMXAMSMMMMXS###
###SAMSSMSXAXXAXSASAAMXSMSAMAMMMMMASAXMAMSSMMMMXMXSXMSSMSXMSSSMSXSMAXAAMXAAMSMMMMSAMXSSMMAXMMSXMXAAAAASXMMSXSMMMSMSASXSMMMASAAAXXASMSMMXSAMXXAX###
###XAMAXAXMMMSSMSASXSXAMXMAXXXAMXSAMMMMAMMMXSAMMMAXAXAMXAAXAAAASAXSXMSASXSMMMAAXXXAMXSAMMSSXXXMSXMXMMXMASXAAXASAXAMXMXMAXMAMMMSAMXMXAAXAMMMMMMM###
###SSMMASMMMAMXAMAMXXMAMAMSMXMXXXMASXAXXMXAASASAMSSMMSSMSSMMSMMMMMAXAMASMXAXMMMMASAMXSAMAMAXXSASXSSSMASMMMSXSAMMMAXXMMSAMMASXAXMSMMSASMMXAAMMSA###
###MXAMAMAXMMMMSMAMXSAMXSXMAMSMMMSAMXMMSAMMMXAXMXMAXAMAXAXMAMMMAAXMASMXMAMMMXXAMMSAMXSMMAMMXMMAMXXAASXSXXXXAMXMMSSMMSAMXSMMSAMXAAXAMXXASXSXSAMM###
###SSMMAMAMMSAAMSMSAXSXMXAMSMAAAAAASAMAXXXSAMSMMSMSMSXMMSMSAMMSSSSXSMSSMSAXMASAXAXAMXMASAASAMMAMXMSMMMXMASMAMAMAAMAMMMXMSAXSAMMSXSMMASMMAAAMMMX###
###MXASXSSMAMMSMAMMMSMSASAMXSSSMSSMSAMXSXXMAXXASAAMMXAXXAASXSAMAMXXMAMXAMMSXXAMMXMAMXMMMMXXAXSSSSMAXAAAXAXAXMSMMMSAMMSAASMMSAXMAXAXMAXXMMMMMMXX###
###SXMMMAMMXSAXMASAMAAAMXAMAXXAMXXMSXMMMMASMMSSMMSMASAMXAMSAMMSAMXSMSMSAXAMXMASAXSXMMXAAMSSSMAMAAXSSXSMSSSSMAXMMMSXSAMMXMMAXAMXMMMSMSMSXSXMAMAM###
###XASMMMSAMMMMXASASMSMXXAMMSSXMASMSMSAAXAXAAXAXXXMXMAMSMXSAMXSASXXAAAMMMMMMMAMMMMAAMSSXSAAAMMMMMMXAMXAXMAAMXMASAMXMXSSSSMSSSMSXSXAAAXSASXSASAA###
###XSMAASMMSAMAMMSAMAMAMSSMAAXMMMMAMASXSSSSMXSMMMMSASAMAMXSMMXXAMXMSMAMAAAXAMAMSASMSMMAMMMSMMXMAAXMASMMMMSMMASXMASXSAXMAXAXAAAAASAMXMXMAMASXSAS###
###SXSMMSAASASMAXMAMAMAMAMXMXSMASMAMMMSXXXAMMAXAXAMASXXASMMASAMSMSMMXSSSSSSXSXSXXXMAXMAMSMAXMAXSXMMAMAXXMAXSXMXMAMMMXMMMMSMSMMMMMMXAXAMAMMMXMAM###
###AAXMAXMMSXMXXXXAMXMXMMSAMMMMASXSMXMXMSXXMAASXSSMMMMSASXSAMAXMASAMMMAAAAAASMXMMMSAMXXSXSAXMMMXAAMSSMMMSMMMMSSMAMMMMSMMAAAXAMXAAXSMSMSMSXSXMAM###
###MAMXMXSAMASAXSSSMMSMAMSXSAAMMSAMXAMAMASXXSMMAXAXAAXMMMMMXSMMMMMAMAMMMMMMAMMAXAAMAMMSMMMMSMSAMMMMXAXMAAMAAAAMXAMAAAAAMSSSMSMSSSXMXAMAXXAMSMAS###
###MAMAMSMAXAMMMMAAXAAMXMMMXMMSAMAMSMXSAMAMMXAMXMXSMSMXSMSAMXAXMXSXMMSAMXAMAMXMMMXSAMXAAAXAAAMMXASXSAMMSMSMMMSXSSSSMSSSMMXXAAAXAMXXMSSSSMXMASAS###
###SASASXSAMXMSAMAMMSXSASASMSAMXSMMXSAMMXMSSSMSSXMAXXASAAXAAMXMAMMAAAXASXXSXMASASXSXXXSSMSMMSMSSMSXMASXMASXMAMXAMAMAAAMMSXMSMMMMMXSAXAXMASXXMXS###
###SAXMSXMXSAASMSMSXXAXXXASAMXXXMXSAMXMXAXAAAAMXSSSSSSSMMSXMSMSMSSMMMMXMMMMMSMSAMASXMXMMMSAAAAXAAMXSAMAMMMAMASMSMAMMMSMASAMXSAAAAAMXMMMSMASXMMM###
###MSMXXAXAXMMMAAAMXMMMSMMMXMSMXSAMXAAMSMMMSMMMAXXAAXAMXXMXXXAAAMXAAMMMXAAXAAXMAMSMMSAAAAMAMSSXMMMAMSMXMASXMXSAASASAAXMMMXMAMXSMMXMMAXAAXAXMXAS###
###AAMXMMMSSSXMSMSMMMAAAAAMAAMAXAXSSMMXAAXAAMMMSSMMMMMMMAXSMMSMSMSMMSAASXSSSSSMAMXAASXSMSSMMAAASAMXSXMASASASAMMMSXSMSXSAMXMSSXXMMSAMSMSSMMSASMS###
###SMSAMXAAAAMMMXMXXMMMMSMSMMMAMMXXXASMSMMSMMMAMAXSXMXMSMXAAAAMXAXXASMMMMAXXAAXMAMMMSAMAXXMMXSMMAXSAXMAMXSXMASAMXXSAMAMMSAAAMMSAASAMXAMXMAAMAMX###
###XXSASMMSSMMAXMASMSMXAMAXAXSAMXAMMMMAXMAAAAMASXMMXSAMAMMMMMSSMXMMMXMMSMSMMXAMXAAAAMAMSMAXMAXASMMMAMMASXMXSAMXMXMSAMSMASMMMMAMMMSAMMSMMXXSSSXS###
###MASXMAMAMXSASXXAAAAMSMSMMMXAMXAXSAASMMSSSMSASAMXASXSASASAMXAXAMSMMSASXMASAMXSMSMXSXMASMMMMXMXAXMAMSASASASXSXSAASMMXMAXXAXXSXSXSAMXMASXAMAMMM###
###MAMASXMAXAMXAMXMMMSMMAXAMAMXMSXMSAXMAXAMXXMXMXMMMSASASAMASMSMMMSAXMASASAMSAMXMAMXMASMXMXAMMXSAMSMXMXSXMAMAAASMMMAXSMXSMAMXMAMMSMMMXMMMMMAMXM###
###MSSXMAMMMSSMMXAXAAXAMXSXMAXSAXAXXMMSMMSSMSXXMASXMXAMMMXSAMXAXSAMMMMAMMMAMAXMASASAAXXXMASAMAMMMMXMAMMMMMSMAMXMAASMMSMMAMASMMAMXXAAAASAMXSXMAS###
###MAMMSSMXAAAAXMSMMXSAMXMAMAXMMSMMAAAXAAMAXXAASAMXXMXMAXMAXXMMSMAXSAMAMXSMXMASASXSMSMXSAMXSMSXSASXSAMAXAAMAMXXXSMSXXXSAAXMXAXXSSSSMSXXASXMXSMX###
###MXSAAAAMMSSMMAMXXXAMSMSAMSMSAMXSSMXSMMSSMMSMMASXXXSSXSMMXMAMAXAMAMSAXXAAASAMASXSXAAMASAAXXMASASASXSSSMSSMSMSXAAXXMASXSMSMSMXMMXAAMMSXMAMASAS###
###SAMMSSMXMAXAXSXAMXMMAMMXXXASXSXXAMMXAXXAXXMXSXMXSMAXSMXAASMMSXMSMASASAMSMXAMSMAXSXXXAXMSSMMMMXMAMAAASAMXAAASAMMMAMXMAMASAXXAMSXMMXMASMXMASMA###
###MASAMXMXMASXMXMASAXSASMSSMXMAMXSAMSMMMXXXMMASAMXMAAMASMSMMAXAAMMXMMMMMXMXXSMMMXMAMMMMSAAMAMXSMMSMXMSMSMMXMSMAXAXXXAMMMAMMSAMXXXMXXMAMXXMMSXM###
###SAMASXXMAXSXMMAXXMMSASAMXAAMAMMMXMXAAAMMMSMASASMMSXSAMXXASXMSSMSAXMMAXAXMAMAMASXXXAAAMMMMAMMXAMXMMXMAMXXMSAXSMMMSSMSSMASXMXMAXMMXMASXXSXMMMX###
###MASAMMASMXSAAASMMMAMXMMMMSXSASXMSASMMSAAAXMASXAAAMAMAMSXMXSAAAXSAMXSSSMSXAMAMAMMMSMMSXXXSMSASXMAAMAMMMSMMSAMMAAAMAXAASASAMSMSMSAMXAMMMXXXAAX###
###SMMMXSXMMASXMMMAMMAXAMMXAXASMSAXMASAAXXAMXSMSMMSXMASAMXAMAXMSSMMASXMAMMMMMMAMASAAAMAXXMXAMXXMMSSMSMSAAXSAMXMSXMMSMMSXMMSAMAAAAXXAMASXAAMSMSM###
###MXAMMSSMMASAXAMAMMASXSAASXMMASXXMAMMMMXMXXSAMXXMASAXMXMAMXMAMXAMAMAXMASAASXMSASMSXMASASXXXXMMMAXMAXXMSSMSSSMSAMAAXAMXMASMSMSMSMAAMMMMMMXSAAA###
###SMMSAXASAAXAMXSSMXMAMXMSMASMAMMMSMSAMXMMMMMMMMASMMMSAMSSMSAMXSSMASMMXMSMMSAAMASMMXMXSAMMMMMSAMXSMSSSSMAMMSXASAMSXMXSSMAXXAMXAMASXMSMSXSAMSMS###
###AAMMMSMMMSSMSAMXAMXMASMAXXMMMXXAAXMASAAAASASAXMAMAAMAMAAASXMMAMMXMAMAMXMXSXMSAMAAAMMMXMAXAASMSMSAAAMMMAMXXMMMXMXASAMAMASMSSMXMAMXMMAXAMMMAMA###
###SMMAAAAAAMAMXXXAXMAXXAXMXSXXSAMXSXMASXMMMSASXMXAMMSXSMSMMMAMXMSXSSMMAMMSAMAMMASMMXSAMXSSMMXXXAAMMMSMXXSXMMMSAMMXSMASAMXXAMMXMMAMSMMMMXMXSASX###
###XAXMSMXMMSAMMMSMSSMSSMASAXXXMASXAXSASAMSAMMMMXSXMAMMAAAMASAMXXAAXAMSAMAAMSAMSXMASAXMAXAMXMASMMSMSAMXMMMASAASASMXXMXMASMMSMXAMMMXSAAMSMSAXMMM###
###SXMMMMSAMSASAAAXAAAAASAMASXMSAMMAMMASAXMAMMAAMMAMAMXMSMSAMMXMMMSMMMSASMMXMAMXASAMMSMMXSMXSAMXAAXMASXMASMMSXSAMXMMXMAXMXAMASXSASXSXMSMAMMXSAM###
###MMXXAXMAMSASMSSSSSMSXSMSMMXMAASXMMMAMXMSAMSMMSSSMMMXXAAMXSSSMAAAAAAMAMXXSSSMSXMASXAXSAMXAMMMSSXXAMXMMXXSAXMMMMMXSASAMXMSMAAASASMXXMAMMMAAMAS###
###XXAMMMMAMXXXAAAMAXAXXMASXAXSXXMXAAMSSXAAAXAAAXXMASAMXMXMASAASMSSSMXMSMMAAAXASMSSMXASMMMMMSAXXXMSMMAXXASMMXMAAAXASAMXAXSAMXSMMXMXSMSSSMMMMSAM###
###MMXMAMSMSXMMMMSMMMSMSMMMMSMSMSMSMMMASMSSSMMMMSASAMASAMSSSMSMMXAMMMXXAAMSMSMMMMXXAXMAAAAAMAMMMXAAAMXSSMMXAASMSMSAMAMASMSAMMAXAASMMAAAAMXAXMXM###
###SMAMAXAAMAAMAAAAXAMAMXAAAXAMAAAMASMMXXAMMAXAMSAMASAAASAMXAAXSAMXAAMXMMMAMAXMXMAMXMAXSMSXSASAAXSXSAMXMAAMSXSAAAMXMXMMMASAMAMASXSAMMMSMMMMMXAM###
###AAMSSSMSSXSSMSSSMSMAMSSSSMAMSMSMAMAXSMSSXSMMMMXMAMMSSMXSMSMXAMXSMSXSAAMASMXMAMASXSSXMAXXSAXMSMAAMMAASMMXMAMMMMMMSMSXMMMAMMXXMASMMXAXAMSSSSSS###
###MXXAXSXXAAXXMAXMAAMXMMXMXMSMXAXMAXXMAAMXMXASXSAMASXXXAXXMXMSMMMXAAAMSMSXXXASXSMSAAXSSXSMMSMAAAMXXXSXSMSXSAAMASAAAAAXAXSXXXSAMXSXSMMMAMAAAAAS###
###XMMSSMSMMMMASXSMSMSSXSMMAXXASXMMSASAMXMAXXAMASASASMSMSMXMAMAAMMMMMSMXMAXXMAXAAXMMMMXSASXAXMMMXAMMMMAMAMAAMMSASMSMMMAMMXMXMSXMASASASMSMMMMMMM###
###MXAXMAXXMASXMASAAAXXAMMMXMMXMAMAAXSSSMSSSMAMXMAMAXAMAAXMXASMSMAAXAXMXSAMMMSMSMMXMASAMXMMMSMSXAXAAAMAMAMXMAAMMSAAAAXAMMAMAMXASMMMMMMAAXMASMXM###
###AMSSMSMSSMSAMAMSMSMMXMASMMSMSMMASMMASAAAAMMMAMXMSMMMSMMSSMSAXMSMSMXSAMASXAAXAAMXMAMASXMXAAAAMAMXSMSMSAMXMMSSMMMXSMXXAXAMAMMXAXAAAXMSMMMAXAAX###
###SAMXAAAAMXMXMXMXXXXMMMASAAAAASXAMAMAMSMSMMMSASMAMAAAXMAXAXMMMAXAAAAMASAMMSSSSSSMMXMXMXXASMSMMASAAASMSAMXAXXAXAMMMASXSSMSASMSMSXSSSMAMAMMSSSS###
###MAAMMMSMSMSMMMMAMXMMAMASMMMXMSMSXMMXMAXAXMXMAXMASXMMSAMMAMMSMAMSMMMSXMAXXXAAAAAMMAMXMSXAMXMASASMMMSASAMSSMSMMSSXMAMAAAASAAAAXAXMXMMXMASXAAAM###
###SSMMSXAXAAAASAMAAAASASAMAXSXXXAXXSAMXMSMSMAMSMMMSAAXMASMSAXAMXMAAMASXSAMMSMMMMMAMASAAMMMMMSAMASXSAMAMAMAAXXXMMXMMMMMMMMMAMXMSMMSAMSXSASMMMMA###
###XAXSASMSMSMMSAXASMMAMMXSAASXMMSSMMASXXSAAXSXXMSAXMMMMAMAXSSMSSSSSMASAMASAAAAXXSMSAMMXMSMAAMMSMMAMASXSMMXSMSXXXSAASASXXAXMASXAAAAAMAAMAMAXMXM###
###MMXSMMXAAXMASXMXXMXAXAXMMMMAMXAXAAAXAXMXMXXAMAMMSSMMMASASXMXMAMAMMMXXSAMMSSMSXXXAMSSMMAMMXMAAAMXMASXAXAXAMXSAASXXSAXMMASXMASMSMSMMXSMAMSXMSS###
###SXAMXMSMMMSMMMMSAXXMMMXXAASMMMMSSMMSMMMSMSSXMAMXAAAAXAMXSAMXMMMAMMMMXMXMXXAMXMMMMXAAASMXSAMSXSMSMASMMMXMAMAAMAMAXMXMSSMSXMXMMMXAMXAXMXSXAAAM###
###AAMSAMASAAAXMAMSAMXSAMSSSMMAAXMAXXMAXAXAAAAASXMMSXMMMMSMXAMXMASASAAXSASMMSAMXAASXMSSMMAAMMXMAAXXMAXAASMMSMSSMAMSMSAMMAAXXMASASMMSMXSXXMAMMAS###
###MSMMMSASMSMXSSXXXMAMASAAMXXXMXMXSMSXSMSMMMMMMAXXXASXXAAAXSSXSASMSXSSMAMAASMMMSMXMAMAMMMMMSAMAMMXMAXSASAAXAMXXMAXASXXXMMMASASXMAMMMMXXAMXXXAX###
###SAMXAMASXAAASXMASMSXMMMSMSMMSAMXSXSXSMAXSSXMSMSAXMMAMSXSXMAMMMSASMMXMMMMMMXSAAXMAMSAMSMMXMXXAXAXMAXMASMMMAMXSMMMXMMSSSXSXMXSMMMMAAAAAMSASMMS###
###SXMMMMASXMSMSAMASXXAMAMAASAASASASAMASMMMAMAMAMXMXXAMXXXMXMAMSAMXMASMMAAAXAAMXSMMMXMMMAAAXMASMSSMMMSMAMAXSXMAXXMXSAXAAMMMAMASAASMSASXSASAMXSM###
###MMSMSMASXMXXXAMAMASXMASMSSMMSAMXMAMAMAMAAMAMAXSXXMAXASMMXSAMSXSXXXMAXSMSMMSSMMMXMAAAXSSMXMASAAMXXMAXMMMMMAMMSASAAXMMSMAXAMASMMSAXXMAMAMXMMAX###
###AMAAXMXMMXMASMMXSAXAXAMMAMXAMXMXMSMMSAMXMSSSMXSAASXMXSAAAXAMSAMMSMSSMMAMAMAXAAAAMMMMMXAMMMASMAMMXMSMSMSASXMAMMMMSXAXXXSSSMASAXMAMAMMMXMASXMX###
###XSMSMSAAMSMAMAAXMASMMSSMAMAMSAMXAMAXMXSXAAAAMAMAMASXXXMMSMMMMAMAAXAMAMAMSXMXSMSSSSXSXXAMXMASXMMXSSMAAASAMMMMXXAMXMSXMAMAAMAXMMMAMAMXSXSASASX###
###ASAMASMMMAMASXMXAAAAAXAMSSSMMAXXMMAMAASMMMSMMASAMMMMSMSXXASMSMMSSSMMMSAMXASAMAMAAAASAMSMSSMMAXAMXAMMMMMXMASAMSXSXAXMASMSMMSSMMXXSASAMAMXSASM###
###MMAMMMSSSMSASMMXMXSMMSSMMAAMSMMSMSMMMAMAXAAASXSMSXAAMXMASAMAAAMAMAXMASMMSAMXMAMMMMMMAMAAXMASMMSMSMMAXAXASMMXMXAMMSMSMMXXAAAMAXSASASAMXMXMAMA###
###XSXMXAAXAAMAMMSASXXAAAAAMSMMAAXAASMMXASMMMXXMAMXXMMMSAMXMAMSSSMXMXMMAMAMAAMXSMSXXAXMXMMSMMMMMAAASXSMSMMMSXXXSMXMAMMSAMAXMMMMAMMAMASAMXSSMAMS###
###XMAMMMMMMXMSMXMASXMMMMSMMAMSXSMMSMASXMSASMSSMAMMMSAASAMXSXMAMAMSSSXMASMAMXXAAXAMSMXMAXAXMMAAMMMSMAXXAAASMMSAAASXXSAMAMXMXASMSMMAMASAMXAAMMSM###
###XXAMXAXSAMXAMMMSMXMAMXMAXAMMMMMXMMMMAAMAMAAXSMSMAMMXXAMXMAMASAMXAMSSXSXMXMMSSMMMAAASAMXSXMXSSMMXMMMSMSMSAASXMMMAAMASAMXSMASAAXSXMXSXMASXMSMM###
###MMSXMASXASXMSAMAAXSAMSMSSSSSXMASMASXSMMMMMXMMSXMMXXSXSMAMAMMSMMMAMASAMXXAXMAXAAXMXMSAMXXAMSMXXXMASAMXXMMXMSAMXMMMMXMASAMMAMMMXMAMAMXXMASMAAA###
###AXAAMSMMMMAAMAMMXMAAXAAMAXAXAAAMMXSAAMAAAMXMXAMMSMMXAMSMSXSMMASMXMASXSMSSSMSSXMSSMXSAMSMSMAASMSSXMAXAXXSMXSXMAMAAXXSXMXSMXSXSASAMMSMMXMAXMMM###
###SMMSMAAXXSXMMSMMASMMSMSMXMASXMASXSMMMSSSXSAMSMXAAAXMXMAXAASASAXXMMASAMAAAAAMAAMAMSAMMMSAAMMSMAAMMXMMMSMMMXXSSXSSXSAMXMMSAMXASXXAXAAASAMMSSXX###
###XAXXMSSMMMASAXASASXAAMXXXAXMASXXXAAAXAAXAMMXAAMSXSMAASMMMSMAMXSAMXAMAMMMSMMMSMMASMXXSAMXMSMAMXAAAASAMXAAMMMXXXAXASXSXMAMAXMMMMMMMSSXSASAAXXA###
###MMMXMXXAAMXMASAMAXMXSMMSSMXXAMMSSSMMSMXMSMMSMSMMAMMSMSAASMMSMASAXAMSXMAMAMXXAAXSMMAAMMMAMAXXSMSMSMMAXXMMSASMMAMMAMXXAMSSSMXMASAMAMMMMMMMMSSX###
###MAAAMMSMMMAMAMXMSMMAXAXAAAMMMSAAMXAXAMAMXMAAMAMXAXAAXXMMSAAXMXSXMXXXASMSSSMMSSMAAMSSSSSSSSSXSAMAMXSMMASASMSAMXXMAMXSAMXAMMASASAMMMASMSMXSAXS###
###SASXSAMAASAMSXMAXAXASAMSSMAAAMMSSSMMASASAMSXSASMSMSMSMSMMMMSMMMXAXMSAMAAAXAXAMXSXMXAMAAAAASAMXMMXMASMMMASMSMMMXXXSAMSAMXMSASXXXMXSAMAAAMMSMA###
###AAMMMASAMSASMAMSSMMMMMAMAMSSXSAAXAASXMAMXMAXMASXMAXAMAXXASAMXXAAXMXAAMMMSXXMASAXASMAMMMMMMMXMMMMMAAASXMAMASASAMSXMASAMXAMMMXAXSAMAXMSMMMAXXS###
###MXMXSAMXXXMAMAMXAXSAAMSSSMAMXMMSMSMMSMXMSMMMSAMAMSMSMAMXAMXSAMXSMSMSSMXAMMSSMMASAXXXMASXXASMAMASMMSAMXMAXXSAMSAAXSXMMXSXMASMAMMAMAXXXAMMASMA###
###SMMXMASXSSMASXSSMMXXMSAAAMSSSXXAAMXMAMAMXAAAMASXMXAXMAMXAXAMMAAXAAAXAMXXAAAAAXAMXMMSXMMSAMXAASMSAAXAMAMMXMMXMMSMMMMMMAMASASMMXSMMMMAMMMMAXAM###
###AXXAXAXAMASASAMXMAXSSMMSMMMAMAMMXMAMMSSSSXMMSMMMAMXMSASMMMMSMSSSSMSMSXMMMMSSMMXSXAXMASAMMMMXMXMMMMSSMSASASXSAXXXMXAAMXSAMMSAXAXXAXMASASMSSSX###
###MSXMXXSASAMXSAMXXAXMAMMAAAMAMMMSMSSMXMAAMMXAXAAAXMXAMMXXAAAAAXAAAAXMMAXXAAMAMSMMMSAMSMXXAAMMXSAXAAAAAXASASASXMXMMMSSSXMMXXXMMMSMXXSASXSAAAMA###
###XMASAMSAMMXAMAMXMMXMAMSMSXSAXXAXMAMXMSMAMSMMSSSMSAMXMMMMSMMMSMMMMMMSXSAMXMMAMXAAAMMXXAMMSXSAASAMSXMMMMAMAMMMAMMSAAMAXAASXSMXAMAXSMMMSAMMMSMS###
###MXAMAXMAMSMMSSMMSASXMMAXMMMMMMMSMASAMMSAAMAMAAAXSMSMSAMXMMXXMASAAXXMAXMMMXMAMXMMSMSAMAMMAAMMMMAMXAXMMMXMAMASXMAXMSSMSSMMAAXXXMXXSAAAMMMXMAXA###
###MMSSXMSAAXAMAAAXMASASMMSXAAAXAAAXXSASMXXMMAMMXMMMAAAMXMAASXMSSSXSSSMAMXAAAMAMXXMMAMMXMMMMMMAXSXMSMMMMMMSMSAXAMMSMAAMAMMMSMMMSAMXSXMMSMSAMXXM###
###XAMAMASMSXXMXSMMMAMXAMAMMSMSXXMMSMSMMXMASMMXSAXAMXMSMXSASXMASXMAMAMMAMSSSMXAXSMSMAMXXSXAASXMXSSXAXAMXAXAAMASXSXAMSSMAMMAAAXMAXMMSXSMSAMXSAMX###
###MMSMMAXXMAXSMXMAMXSAMXAMMXSXXSMXXAXAAMMASAMAMXSMSAAAAXSMMAMXMAXXMAMSXMMAAMMSMSAAXAMSXMAMMMAMMMMSMSSMSASMMMMAAXMMXXXMAMMSSSMMSMSXMASAMXMAXASM###
###MAAAMXSAMMMSAMSMSAMAXSXSXXASAMMASMMMMSMASXMASXMAAMMMSMSASXMASMMXMAMMMMMMXMAXAMSMMSSMAMASMSSMAAAXMAMXAAAXASMMXMMSAMSSMSMAAMASMAXAMAMMMMMMXAMA###
###MSSSMASAASXMAMMXMASAMMXXXAMMSMAASAAXSXMASASASAMAMXSXAAMAMSAMXAAXSMSAAXASMSAMXMASAXAMXAASMAASXMSSMASAMXMAMSAXASXAASAAXAXMASXMMXMMMMSAAXAAMSXS###
###XXAXMASXMMMSAMXAXMAMSAMXASXSMMMSSMMMMSMASMMXSMMAXMASMSMXMXMSAMXXXASMSSMSXMASASMSXSAMXMMSMSMMXAXXXASXXMASMSXMASXSSMXSMMXXMAMXXXXXSSSMSSXXXMAX###
##################################################################################################################################################
##################################################################################################################################################
##################################################################################################################################################"""

erg = 0
liste = sample.split("\n")

for x in range(len(liste)):
    for y in range(len(liste[x])):

        # nach rechts
        if liste[x][y] == "X" and liste[x][y + 1] == "M" and liste[x][y + 2] == "A" and liste[x][y + 3] == "S":
            erg += 1
        # nach links
        if liste[x][y] == "X" and liste[x][y - 1] == "M" and liste[x][y - 2] == "A" and liste[x][y - 3] == "S":
            erg += 1

        # nach unten
        if liste[x][y] == "X" and liste[x + 1][y] == "M" and liste[x + 2][y] == "A" and liste[x + 3][y] == "S":
            erg += 1
        # nach oben
        if liste[x][y] == "X" and liste[x - 1][y] == "M" and liste[x - 2][y] == "A" and liste[x - 3][y] == "S":
            erg += 1

        # nach unten diagonal rechts
        if liste[x][y] == "X" and liste[x + 1][y + 1] == "M" and liste[x + 2][y + 2] == "A" and liste[x + 3][
            y + 3] == "S":
            erg += 1
        # nach unten diagonal links
        if liste[x][y] == "X" and liste[x + 1][y - 1] == "M" and liste[x + 2][y - 2] == "A" and liste[x + 3][
            y - 3] == "S":
            erg += 1

        # nach oben diagonal rechts
        if liste[x][y] == "X" and liste[x - 1][y + 1] == "M" and liste[x - 2][y + 2] == "A" and liste[x - 3][
            y + 3] == "S":
            erg += 1
        # nach oben diagonal links
        if liste[x][y] == "X" and liste[x - 1][y - 1] == "M" and liste[x - 2][y - 2] == "A" and liste[x - 3][
            y - 3] == "S":
            erg += 1

print(erg)
